baseURL = "https://docs.influxdata.com/"
languageCode = "en-us"
title = "InfluxDB Documentation"

# Git history information for lastMod-type functionality
enableGitInfo = true

# Syntax Highlighting
pygmentsCodefences = true
pygmentsUseClasses = true

# Preserve case in article tags
preserveTaxonomyNames = true

# Generate a robots.txt
enableRobotsTXT = true

# Markdown rendering options
[blackfriday]
hrefTargetBlank = true
smartDashes = false

[taxonomies]
  "influxdb/v2/tag" = "influxdb/v2/tags"
  "influxdb/cloud/tag" = "influxdb/cloud/tags"
  "influxdb/cloud-serverless/tag" = "influxdb/cloud-serverless/tags"
  "influxdb/cloud-dedicated/tag" = "influxdb/cloud-dedicated/tags"
  "influxdb/clustered/tag" = "influxdb/clustered/tags"
  "flux/v0/tag" = "flux/v0/tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = false

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[outputFormats.json]
  mediaType = "application/json"
  baseName = "pages"
  isPlainText = true
