plugins:
  - '../openapi/plugins/docs-plugin.js'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB v3 Cloud Dedicated

apis:
  management@0:
    root: management/openapi.yml
  v2@2:
    root: v2/ref.yml
    x-influxdata-default: true
  v1-compatibility@2:
    root: v1-compatibility/swaggerV1Compat.yml
