settings:
  bullet: "-"

plugins:
  # Before you can configure plugins for remark here, you need to add them to
  # the `devDependencies` in the `package.json` file--for CI: `/.ci/app/package.json`.
  - remark-gfm
  - remark-frontmatter
  - remark-lint-frontmatter-schema
  - remark-lint-no-shell-dollars
  # Check that markdown is consistent (list items have the same indentation)
  - remark-preset-lint-consistent
  # - remark-preset-lint-markdown-style-guide
  # - remark-preset-lint-recommended