name: 'Setup Documentation Environment'
description: 'Sets up Node.js environment and installs dependencies for documentation workflows'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install
      shell: bash