plugins:
  - '../../openapi/plugins/docs-plugin.cjs'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB 3 Serverless

apis:
  v2@2:
    root: v2/ref.yml
    x-influxdata-docs-aliases:
      - /influxdb3/cloud-serverless/api/
  v1-compatibility@2:
    root: v1-compatibility/swaggerV1Compat.yml
    x-influxdata-docs-aliases:
      - /influxdb3/cloud-serverless/api/v1/
