# Production overrides for CI/CD builds
baseURL: 'https://docs.influxdata.com/'

# Production environment parameters
params:
  env: production
  environment: production

# Enable minification for production
minify:
  disableJS: false
  disableCSS: false
  disableHTML: false
  minifyOutput: true

# Production asset processing
build:
  writeStats: false
  useResourceCacheWhen: "fallback"
  buildOptions:
    sourcemap: false
    target: "es2015"

# Asset processing configuration
assetDir: "assets"

# Mount assets for production
module:
  mounts:
    - source: assets
      target: assets
    - source: node_modules
      target: assets/node_modules

# Disable development server settings
server: {}

# Suppress the warning mentioned in the error
ignoreLogs:
  - 'warning-goldmark-raw-html'