/**
 * Tests for the Markdown autodiscovery surfaces:
 *
 *   1. <link rel="alternate" type="text/markdown"> in <head>
 *      (layouts/partials/header/markdown-alternate.html)
 *   2. /sitemap-md.xml (layouts/index.sitemapmd.xml)
 *   3. /robots.txt advertises both sitemaps
 *
 * Background: PLAN.md / AI-visibility-for-InfluxDB.md § 5.4.
 *
 * Path-only assertions for the head-link href (new URL(href).pathname) —
 * hugo server rewrites baseURL to http://localhost:1315 so full-URL
 * assertions would fail in dev.
 *
 * Note: /<product>/llms-full.txt is NOT tested here. Those files are
 * generated by scripts/build-llms-full-txt.js *after* Hugo, so they don't
 * exist when running against `hugo server`. See scripts/__tests__/ for
 * the build script's unit test.
 */

const BASE = 'http://localhost:1315';

const ALTERNATE_SELECTOR = 'link[rel="alternate"][type="text/markdown"]';

/**
 * Visit url and assert the Markdown alternate link's pathname matches expected.
 * @param {string} url
 * @param {string} expectedPath - Exact pathname
 */
function assertAlternatePath(url, expectedPath) {
  cy.visit(`${BASE}${url}`);
  cy.get(ALTERNATE_SELECTOR)
    .should('have.attr', 'href')
    .then((href) => {
      expect(new URL(href).pathname).to.equal(expectedPath);
    });
}

/**
 * Visit url and assert no Markdown alternate link is emitted.
 * @param {string} url
 */
function assertNoAlternate(url) {
  cy.visit(`${BASE}${url}`);
  cy.get(ALTERNATE_SELECTOR).should('not.exist');
}

describe('Markdown autodiscovery', () => {
  // Feature-board pages load a third-party productboard script that
  // throws cross-origin "Script error." in Cypress. Swallow those — they
  // don't affect the head-link rendering we're verifying.
  Cypress.on('uncaught:exception', (err) => {
    if (err.message.includes('Script error')) return false;
    return undefined;
  });

  describe('head <link rel="alternate" type="text/markdown">', () => {
    it('emits on a regular page', () => {
      assertAlternatePath(
        '/influxdb3/core/install/',
        '/influxdb3/core/install/index.md'
      );
    });

    it('emits on a section landing page', () => {
      assertAlternatePath('/influxdb3/core/', '/influxdb3/core/index.md');
    });

    it('emits on a deep page in a different product (not Core-specific)', () => {
      assertAlternatePath(
        '/telegraf/v1/configuration/',
        '/telegraf/v1/configuration/index.md'
      );
    });

    it('omits the alternate on feature-board layout', () => {
      assertNoAlternate('/influxdb3/core/feature-board/');
    });

    it('omits the alternate on noindex page', () => {
      assertNoAlternate('/telegraf/v1/__tests__/shortcodes/');
    });
  });

  describe('/sitemap-md.xml', () => {
    it('is served as XML and parses', () => {
      cy.request('/sitemap-md.xml').then((res) => {
        expect(res.status).to.equal(200);
        expect(res.headers['content-type']).to.match(/xml/);
        expect(res.body).to.include('<urlset');
        expect(res.body).to.include('</urlset>');
      });
    });

    it('emits URLs ending in index.md', () => {
      cy.request('/sitemap-md.xml').then((res) => {
        const locs = [...res.body.matchAll(/<loc>([^<]+)<\/loc>/g)].map(
          (m) => m[1]
        );
        expect(locs.length).to.be.greaterThan(100);
        expect(locs.every((url) => url.endsWith('/index.md'))).to.be.true;
      });
    });

    it('URL count is close to /sitemap.xml (within reasonable delta)', () => {
      cy.request('/sitemap-md.xml').then((mdRes) => {
        cy.request('/sitemap.xml').then((htmlRes) => {
          const mdCount = [...mdRes.body.matchAll(/<loc>/g)].length;
          const htmlCount = [...htmlRes.body.matchAll(/<loc>/g)].length;
          // sitemap-md excludes feature-board, noindex, and taxonomy pages.
          // It should be lower than the HTML sitemap but on the same order.
          expect(mdCount).to.be.greaterThan(htmlCount * 0.5);
          expect(mdCount).to.be.lessThan(htmlCount);
        });
      });
    });

    it('does not include feature-board or noindex pages', () => {
      cy.request('/sitemap-md.xml').then((res) => {
        expect(res.body).to.not.include('feature-board');
        expect(res.body).to.not.include('__tests__/shortcodes');
      });
    });
  });

  describe('/robots.txt', () => {
    it('lists both sitemap.xml and sitemap-md.xml', () => {
      cy.request('/robots.txt').then((res) => {
        expect(res.status).to.equal(200);
        expect(res.body).to.match(/Sitemap:\s+\S+\/sitemap\.xml/);
        expect(res.body).to.match(/Sitemap:\s+\S+\/sitemap-md\.xml/);
      });
    });
  });
});
