plugins:
  - '../../openapi/plugins/docs-plugin.cjs'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB v2 Cloud

apis:
  v2@2:
    root: influxdb-cloud-v2-openapi.yaml
    x-influxdata-docs-aliases:
      - /influxdb/cloud/api/
      - /influxdb/cloud/api/v1/
      - /influxdb/cloud/api/v1-compatibility/
